easy_admin:
    site_name: Administrador
    design:
        menu:
          - { route: 'easyadmin', label: 'Inicio', icon: 'home' }
          - { entity: 'Cliente', label: 'Clientes', icon: 'user-friends' }
          - { entity: 'Factura', label: 'Facturas', icon: 'sticky-note' }
          - { entity: 'Plan', label: 'Planes', icon: 'atlas' }
          - { entity: 'Notificacion', label: 'Notificaciones', icon: 'atlas' }
    formats:
        date:   'd/m/Y'
    entities:
        # List the entity class name you want to manage
        Cliente:
          class: App\Entity\Cliente
          list:
            fields: ['id', 'nombre', 'direccion', 'dni','celular', { property: 'mail', type: 'email' }, plan]
          new:
            fields: ['nombre', 'apellido', 'direccion', 'dni','celular', { property: 'mail', type: 'email' }, plan]
        Factura:
          class: App\Entity\Factura
          list:
            fields:
              - id 
              - fechaGenerada
              - fechaVencimiento
              - valor
              - { property: pagada , type: boolean }
              - fechaDePago
        Plan:
          class: App\Entity\Plan
          new:
            fields: ['descripcion','valor']
        Notificacion:
          class: App\Entity\Notificacion
          list:
            fields: ['id', 'nid', 'topic', 'time']